version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.2
    - 11.1.3
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: rc-footer
    versions:
    - 0.6.3
    - 0.6.5
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.23
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.30
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.803.29
  - dependency-name: jquery
    versions:
    - 3.5.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: tslint
    versions:
    - 5.20.1
