# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
        
      - run: |
          yarn build ng-antd
          yarn theme
          yarn typedoc
          yarn extract-api
          yarn build --prod --outputHashing=none

      - run: |
          gzip -k ./dist/ng-antd/bundles/ng-antd.umd.min.js
          gzip -k ./dist/ng-antd-site/main-es5.js
          gzip -k ./dist/ng-antd-site/main-es2015.js

      - store_artifacts:
          path: ./dist/ng-antd/bundles/ng-antd.umd.min.js.gz
          destination: ng-antd.umd.min.js.gz

      - store_artifacts:
          path: ./dist/ng-antd-site/main-es5.js
          destination: site-main-es5.js.gz

      - store_artifacts:
          path: ./dist/ng-antd-site/main-es2015.js
          destination: site-main-es2015.js.gz

  test:
    docker:
      - image: circleci/node:lts-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      
      - run: yarn test ng-antd --progress=false --watch=false

      - run: yarn codecov

  lint:
    docker:
      - image: circleci/node:lts-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
        
      - run: yarn lint

  integration:
    docker:
      - image: circleci/node:lts-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
        
      - run: yarn generate && yarn integration:cli

  deploy:
    docker:
      - image: circleci/node:lts-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "8c:8a:44:df:c9:3d:a5:a6:3e:c1:69:0e:1a:9b:6d:6b"

      - run: |
          git config --global user.email "trotyl@qq.com"
          git config --global user.name "Trotyl Yu"

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: |
          yarn build ng-antd
          yarn gh-build

      - run: yarn deploy

  noop:
    docker:
      - image: circleci/node:lts-browsers

    working_directory: ~/repo

    steps:
      - run: echo noop

workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          filters:
            branches:
              ignore: /gh-pages/
      - test:
          filters:
            branches:
              ignore: /gh-pages/
      - lint:
          filters:
            branches:
              ignore: /gh-pages/
      # - integration:
      #     filters:
      #       branches:
      #         ignore: /gh-pages/
      - deploy:
          filters:
            branches:
              only: master
      - noop:
          filters:
            branches:
              only: gh-pages
