# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
        
      - run: |
          yarn generate
          yarn add file:./publish
          yarn theme
          yarn typedoc
          yarn extract-api
          yarn extract-demo
          yarn build:es5
          yarn build:es2015

      - run: |
          gzip -k publish/bundles/ng-antd.umd.min.js
          gzip -k dist/main.js
          gzip -k dist2015/main.js

      - store_artifacts:
          path: ./publish/bundles/ng-antd.umd.min.js.gz
          destination: ng-antd.umd.min.js.gz

      - store_artifacts:
          path: ./dist/main.js.gz
          destination: docs-main-es5.bundle.js.gz

      - store_artifacts:
          path: ./dist2015/main.js.gz
          destination: docs-main-es2015.bundle.js.gz

  test:
    docker:
      - image: circleci/node:8.9-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      
      - run: yarn test

      - run: yarn codecov

  lint:
    docker:
      - image: circleci/node:8.9-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
        
      - run: yarn lint

  integration:
    docker:
      - image: circleci/node:8.9-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
        
      - run: yarn generate && yarn integration:cli

  deploy:
    docker:
      - image: circleci/node:8.9-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "8c:8a:44:df:c9:3d:a5:a6:3e:c1:69:0e:1a:9b:6d:6b"

      - run: |
          git config --global user.email "trotyl@qq.com"
          git config --global user.name "Trotyl Yu"

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn gh-build

      - run: yarn deploy

  noop:
    docker:
      - image: circleci/node:8.9-browsers

    working_directory: ~/repo

    steps:
      - run: echo noop

workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          filters:
            branches:
              ignore: /gh-pages/
      - test:
          filters:
            branches:
              ignore: /gh-pages/
      - lint:
          filters:
            branches:
              ignore: /gh-pages/
      - integration:
          filters:
            branches:
              ignore: /gh-pages/
      - deploy:
          filters:
            branches:
              only: master
      - noop:
          filters:
            branches:
              only: gh-pages
